# Numpy

In [26]:
#Numpy开源数据科学计算
import numpy as np
a = np.array([[0,1,2,3,4,5],
             [6,4,8,9,6,9]])
a.ndim  # 秩，维度的数量

2

In [27]:
a.shape  #对象的尺度，对于矩阵，n行m列

(2, 6)

In [28]:
a.size #ndarray对象元素的个数 == n * m的值

12

In [29]:
a.dtype  # 数据类型

dtype('int32')

In [24]:
a.size

2

# Numpy 数组创建方法

In [30]:
# 1.从python中的列表，元组中创建ndarray数组
# 2.使用NumPy函数创建ndarray，如 arange,ones,zeros等
# 3.从字节流（raw bytes）中创建ndarray
# 4.从文件中读取特定格式，创建ndarray数组


In [31]:
# 1
x = np.array([1,2,3,1,4])
print(x)

[1 2 3 1 4]


In [33]:
x = np.array((1,4,5,7,8,2))
print(x)

[1 4 5 7 8 2]


In [35]:
x = np.array([[1,2,3,4,5],(5,7,9,7,5)])
print(x)

[[1 2 3 4 5]
 [5 7 9 7 5]]


In [36]:
# 2

In [40]:
x = np.arange(4)
print(x*4)

[ 0  4  8 12]


In [41]:
x = np.ones((3,6))
print(x)

[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]


In [42]:
x = np.zeros((3,6))
print(x)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [47]:
x = np.full((2,3),2)  # 几行几列，val = 2
print(x)

[[2 2 2]
 [2 2 2]]


In [51]:
x = np.eye(5) #对角线值为1
x

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [52]:
# Numpy一元函数计算
a = np.arange(24).reshape((2,3,4))
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [53]:
np.square(a)

array([[[  0,   1,   4,   9],
        [ 16,  25,  36,  49],
        [ 64,  81, 100, 121]],

       [[144, 169, 196, 225],
        [256, 289, 324, 361],
        [400, 441, 484, 529]]], dtype=int32)

In [54]:
np.sqrt(a)

array([[[ 0.        ,  1.        ,  1.41421356,  1.73205081],
        [ 2.        ,  2.23606798,  2.44948974,  2.64575131],
        [ 2.82842712,  3.        ,  3.16227766,  3.31662479]],

       [[ 3.46410162,  3.60555128,  3.74165739,  3.87298335],
        [ 4.        ,  4.12310563,  4.24264069,  4.35889894],
        [ 4.47213595,  4.58257569,  4.69041576,  4.79583152]]])

In [56]:
np.modf(a)

(array([[[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]],
 
        [[ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.]]]), array([[[  0.,   1.,   2.,   3.],
         [  4.,   5.,   6.,   7.],
         [  8.,   9.,  10.,  11.]],
 
        [[ 12.,  13.,  14.,  15.],
         [ 16.,  17.,  18.,  19.],
         [ 20.,  21.,  22.,  23.]]]))

In [58]:
# 单元小结
   # Numpy : 一维，二维，三维，多维，高维
    #ndarry: .ndim .shape .size .dtype .itemsize
    #np.arange(n) np.ones(shape) np.zeros(shape) np.full(shape,val)
    #np.eye(n) np.ones_like(a) np.zeros_like(a) np.full_like(a,val)
    #数组的索引和切片


# Numpy数据存取和函数

In [60]:
#  CSV文件 
#np.savetxt(frame,array,fmt='%.18e',delimiter=None)
#1.frame:文件，字符串货产生器，可以是.gz或.bz2的压缩文件
#2.array:存入文件的数组
#3.fmt:写入文件的格式，例如：%d,%.2f,%.18e
#4.delimiter:分割字符串，默认是任何空格


In [74]:
a = np.arange(100).reshape(5,20)
np.savetxt('a.csv',a,fmt ='%d',delimiter =',')

In [76]:
b = np.loadtxt('a.csv',dtype = np.int,delimiter =',')
print(b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


In [77]:
# 多维数据的存储

In [80]:
#a.tofile(frame,sep='',format='%s')
a = np.arange(100).reshape(5,10,2)
a.tofile("b.bat",sep=",",format = '%d')

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [113]:
a = np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])