In [1]:
import numpy as np
def npSum():
    a = np.array([0,1,2,3,4])
    b = np.array([5,6,5,4,8])
    c = a**2 + b**3
    return c
print(npSum())

[125 217 129  73 528]


In [5]:
x = np.array([0,1,2,3,6,4])
print(x)

[0 1 2 3 6 4]
Object `clip` not found.


In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Matplotlib